name: CI/CD with Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t flask-secure-app .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy FS Scan
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Run Trivy Image Scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL flask-secure-app